### ISSUE TITLE
Security issue in meow 5 dependency

### ISSUE THREAD

**Issue by fernandopasik** [sindresorhus/replace-in-files-cli#11]
The dependency `meow` 5 depends on `yargs-parser` which is locked on version 10 and has a security issue.

The best course of action might be update `meow` to latest version

**Comment by fernandopasik** [comment]
https://github.com/advisories/GHSA-p9pc-299p-vxgp

**Comment by sindresorhus** [comment]
To be clear, this "vulnerability" doesn't actually affect Meow as it doesn't support nested flags.

**Comment by sindresorhus** [comment]
Fixed in v1.0.0.
