### ISSUE TITLE
Javascript flavor CLI

### ISSUE THREAD

**Issue by Izocel** [sindresorhus/replace-in-files-cli#18]
replace-in-files --regex=`/M.*\s*4*,/gm` --replacement="replaced2" replaceMe.md

Use file:

"Name",     "replaced", "Age", "Height (in)", "Weight (lbs)"
"Alex",       "M",   41,       74,      170
"Bert",       "M",   42,       68,      166
"Carl",       "M",   32,       70,      155
"Dave",       "M",   39,       72,      167
"Elly",       "F",   30,       66,      124
"Fran",       "F",   33,       66,      115
"Gwen",       "F",   26,       64,      121
"Hank",       "M",   30,       71,      158
"Ivan",       "M",   53,       72,      175
"Jake",       "M",   32,       69,      143
"Kate",       "F",   47,       69,      139
"Luke",       "M",   34,       72,      163
"Myra",       "F",   23,       62,       98
"Neil",       "M",   36,       75,      160
"Omar",       "M",   38,       70,      145
"Page",       "F",   31,       67,      135
"Quin",       "M",   29,       71,      176
"Ruth",       "F",   28,       65,      131

dont match regex101 results replaced with unmatched results

![image](https://user-images.githubusercontent.com/68454661/178609679-a4bd3915-3087-4fd7-b47e-c6521d7a3170.png)

![image](https://user-images.githubusercontent.com/68454661/178609767-d1639edf-db06-46be-a04d-f7163dcaa857.png)

**Comment by sindresorhus** [comment]
Please see the regex example in the CLI help. You cannot pass a JS regex literal. You must pass a regex string.
