### ISSUE TITLE
Option can escape the executable and inject cmd commands...

### ISSUE THREAD

**Issue by Izocel** [sindresorhus/replace-in-files-cli#19]
![image](https://user-images.githubusercontent.com/68454661/178611123-dee321c1-73a5-47e5-af32-da6df5a97892.png)

![image](https://user-images.githubusercontent.com/68454661/178611167-7564e9da-6e63-4372-893b-8ad8fa02b81d.png)

**Comment by Izocel** [comment]
imgagine the regex contains:
 rm -rf

**Comment by sindresorhus** [comment]
Flag quoting/escaping has nothing specifically to do with this package. It's handled by the shell you use.

**Comment by Izocel** [comment]
how could i do this command then ? plz
