### ISSUE TITLE
Provide `api.js` as standalone package

### ISSUE THREAD

**Issue by mesqueeb** [sindresorhus/replace-in-files-cli#20]
To have better security I try to limit node packages to only using ones provided by sindresorhus.

Therefore it would be cool if the `api.js` of this is made available as a standalone package as well.

**Comment by sindresorhus** [comment]
Done: https://github.com/sindresorhus/replace-in-files-cli/releases/tag/v2.1.0

I plan to make it a proper package at some point with docs and stuff, but it's not something I have time to do right now.
